### ISSUE TITLE
Infinite Scroller: reverse infinite scrolling?

### ISSUE THREAD

**Issue by cloudspeech** [GoogleChrome/ui-element-samples#107]
Hi,

I'd like to extend the infinite-scroller example for reverse infinite-scrolling, as is arguably more natural for chat-like applications where you start with the latest messages at the bottom of the list.

Any guidance on how to modify/extend the existing code to support this use case?

Cheers, Markus

**Comment by surma** [comment]
Yeah, that should work. Just move down the content and add new content above. I can’t really help you implement it, but it’s certainly possible.

**Comment by nbashkankov** [comment]
@surma Please check my PR for reverse: https://github.com/GoogleChromeLabs/ui-element-samples/pull/110
