### ISSUE TITLE
Documentation on how to use?

### ISSUE THREAD

**Issue by carlinyuen** [GoogleChrome/ui-element-samples#112]
https://github.com/GoogleChromeLabs/ui-element-samples/blob/5490755a858ca44d0befe4f869e295db22092cfc/parallax/scripts/parallax.js#L18

Hey there, was wondering if you could provide more documentation on how to use this? I understand I could parse through all the code to figure it out instead, but thought it might be nice to provide some references.

**Comment by surma** [comment]
Most of these items are not really a library but part of a YouTube series or article. All of these are listed on the [website](https://googlechromelabs.github.io/ui-element-samples/).

In your case, the article for the parallax scroller can be found here: https://developers.google.com/web/updates/2016/12/performant-parallaxing
