### ISSUE TITLE
we have a question about asynchronous request data issues?

### ISSUE THREAD

**Issue by mexhfl** [GoogleChrome/ui-element-samples#115]
If I scroll too fast, the older request has not yet been completed, will it be requested in sequence? For example, if I scroll from 2 to 5, will components request 2,3,4 in order or directly request 5 of the data?

**Comment by mexhfl** [comment]
this question is about infinite-scroller

**Comment by surma** [comment]
Yes it will fetch 2, 3, 4 and 5, as explained in the [comment](https://github.com/GoogleChromeLabs/ui-element-samples/blob/gh-pages/infinite-scroller/scripts/infinite-scroll.js#L36-L44).

**Comment by mexhfl** [comment]
thanks
