### ISSUE TITLE
Swipeable Cards and Side Nav are not working on iOS

### ISSUE THREAD

**Issue by carlosagsmendes** [GoogleChrome/ui-element-samples#15]
Tested with Safari and Chrome on iPhone 6

**Comment by paullewis** [comment]
Thanks, I'll take a look now.

**Comment by paullewis** [comment]
Oh it's likely the use of ES2015 code.

**Comment by paullewis** [comment]
Yeah:

```bash
babel --presets=es2015 swipeable-cards/cards.js --out-file swipeable-cards/cards-es5.js
babel --presets=es2015 side-nav/side-nav.js --out-file side-nav/side-nav-es5.js
```
"fixes" it. I'll add a note to the README.

**Comment by ricardobrandao** [comment]
The [online samples](https://googlechrome.github.io/ui-element-samples/) have not been updated yet, right?

**Comment by paullewis** [comment]
Updated how? I don't necessarily intend to put out ES5 versions of the code; it adds a level of complexity, which wasn't the intention of the project.

**Comment by ricardobrandao** [comment]
Ok, I didn't notice that. So the online samples won't work until the browsers fully support classes. Maybe that could be added to the readme? :)

**Comment by paullewis** [comment]
I added it yesterday :D https://github.com/GoogleChrome/ui-element-samples#es2015-and-es5-transpilation

**Comment by ricardobrandao** [comment]
Ah, sorry! Thanks :+1:
