### ISSUE TITLE
server-side-rendering demo pacakge.json npm install error

### ISSUE THREAD

**Issue by stursby** [GoogleChrome/ui-element-samples#50]
`npm install` in the [server-side-rendering demo](https://github.com/GoogleChrome/ui-element-samples/tree/gh-pages/server-side-rendering) isn't working. I believe it's the trailing `,` on [line 12](https://github.com/GoogleChrome/ui-element-samples/blob/gh-pages/server-side-rendering/package.json#L12). Removing it fixed it for me.

My new `package.json`

``` json
{
  "name": "server-side-rendering",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "express": "^4.14.0",
    "handlebars": "^4.0.5",
    "spdy": "^3.4.0",
    "http2": "^3.3.5",
    "mz": "^2.4.0"
  },
  "devDependencies": {}
}
```

**Comment by surma** [comment]
🙄 Thanks

**Comment by stursby** [comment]
No problem! Did you get to the bottom of `spdy` still serving up HTTP/1 issue? I cloned the repo, booted up the server and also got HTTP/1 (using Node 4).

**Comment by surma** [comment]
Yeah I also tweeted about it. Node 4 is the issue. It works just fine with
node 5. Get nvm :)
