### ISSUE TITLE
Advanced Router - HTML in sc-view not appearing

### ISSUE THREAD

**Issue by itsMattShull** [GoogleChrome/ui-element-samples#53]
I've been wrestling with this all day.  If I put simple text inside <sc-view> then it shows the content.  But if I add any html inside <sc-view> it won't show, unless it's the initial load of the page.  I've been tinkering with _loadView in SCView.  If I console out `const newView` it will show <sc-view> with all of the HTML properly inside.  It appears that it's breaking down somewhere in:

```
newView.childNodes.forEach(node => {
    this._view.appendChild(node);
});

this.appendChild(this._view);
```

Has anyone else experienced this?

**Comment by oldergod** [comment]
Could you show a not working solution? Maybe fork the repo and show a branch of yours?

**Comment by itsMattShull** [comment]
Sure: https://github.com/derekshull/styleguide

Should be able to pull it down and run `npm install` and `gulp watch` to see what I'm talking about.  You can see what I'm talking about.  Whenever you choose a link inside the the sidenav look in the console and you'll see that the xhr is pulling in the correct <sc-view> with the proper content inside the element.

**Comment by oldergod** [comment]
Can you reproduce it with the ui-element-samples code?

**Comment by itsMattShull** [comment]
Yeah: https://github.com/derekshull/ui-element-samples/tree/gh-pages/router-advanced

If you pull it down, go to the router-advanced folder in terminal, run `python -m SimpleHTTPServer 8000`, and go to localhost:8000.  If you try to go to the About page you'll get nothing, just like my styleguide example.  Then if you go to localhost:8000/about you'll see the About content but if you click on Home you won't see that content.

**Comment by oldergod** [comment]
I see your problem and it does not work because you broke the code.

inside the [index.html](https://github.com/derekshull/ui-element-samples/blob/gh-pages/router-advanced/index.html) file, you removed the `visible` class and added the `remote` attribute for `view-home`, and vice-versa for `view-about`. Here is the [diff](https://github.com/GoogleChrome/ui-element-samples/compare/gh-pages...derekshull:gh-pages#diff-e5a57fb633681012535edb7cdd17b284R37).
You should not do this, as the index.html is when you access the page via the root `/`. Fix this and it works fine.

You would need to fix the other html files accordingly as well.

**Comment by itsMattShull** [comment]
I believe I had it set up properly.  I'll have a look.  What appears to work is what I did here: https://github.com/GoogleChrome/ui-element-samples/pull/54

By using `this.innerHTML = newView.innerHTML;` instead of 

```
newView.childNodes.forEach(node => {
    this._view.appendChild(node);
});

this.appendChild(newView.innerHTML);
```

Seems to work well.  Would there be any reason not to do this?

**Comment by itsMattShull** [comment]
@oldergod I see where you were referring to.  I had it mixed up for a bit, but it doesn't appear to be the cause of what I was experiencing.

**Comment by surma** [comment]
Not using `innerHTML` was a conscious decision. Using `innerHTML` serializes the entire DOM to a string just to deserialize it right after. The current code _should_ be doing exactly the same.

I took the current `advanced-router` code and changed line 38 of `about/index.html` to

``` html
<sc-view class="view-about visible" route="^/about/(.*)">
  <div>About <a href="x.com">lol</a></div>
</sc-view>
```

and it still works fine, both on initial page load as well as on navigation.

So I can’t reproduce, but I am curious as to what is going wrong on your end.

**Comment by surma** [comment]
Ah, I think I found the issue and I also found the solution 💃 

So I changed `about/index.html:38` to

```html
```

**Comment by surma** [comment]
Ah I think I found the issue and I also found a solution 💃 

After changing `about/index.html:38` to

``` html
<sc-view class="view-about visible" route="^/about/(.*)">
  <div>About <a href="x.com">lol</a></div>
  <a href="kek.com">kek</a>
</sc-view>
```

I could reproduce the issue as in the “kek” link never showed up.

`HTMLElement.prototype.appendChild()` is a smart beast in that it detaches a node from its previous parent before attaching it to the new one. `forEach()` doesn’t handle mutating the iterable it is iterating over very well (see [this JSBin](https://jsbin.com/kufura/edit?js,console)) 

My solution is changing this

``` js
      newView.childNodes.forEach(node => {
        this._view.appendChild(node);
      });
      this.appendChild(this._view)
```

to

``` js
      newView.childNodes.forEach(node => {
        this._view.appendChild(node.cloneNode(true));
      });
      this.appendChild(this._view)
```

@derekshull Do you want to do the honors to fix this in your PR or do you want me to do it?

**Comment by surma** [comment]
Actually, even better would be:

``` js
      while(newView.firstChild) {
         this._view.appendChild(newView.firstChild);
      }
      this.appendChild(this._view);
```

**Comment by itsMattShull** [comment]
Great! I'll fix this in my local, test, then change the pull request to reflect the changes. Thanks @surma!

**Comment by itsMattShull** [comment]
I've made the changes in the pull request.  I'll go ahead and close the issue.
