### ISSUE TITLE
Parallax: background problem when reducing window height

### ISSUE THREAD

**Issue by criscmaia** [GoogleChrome/ui-element-samples#68]
Tested only on Chrome V54 - Windows 10.

When you first load the page, everything works fine. But as soon as you reduce the height of the browser window, white space starts showing up everywhere. Same problem doesn't happen when resizing horizontally.

**Comment by paullewis** [comment]
Thanks for the report. Someone mentioned this on Twitter, I believe. We'll take a look!

/cc @flackr and @surma
