### ISSUE TITLE
Drag from left to right open menu

### ISSUE THREAD

**Issue by erikandershed** [GoogleChrome/ui-element-samples#75]
Love this menu! 

How do I do to make the menu open on mobile by only (touch) drag from the left (start of screen) and to the right. So it work like an native menu function. 

Thanks for a super menu!!

Best regards,
/Erik

**Comment by surma** [comment]
A common solution is to define a small padding on the border of the screen. if a `touchmove` started in that region, you can `preventDefault()` and pull in the sidebar.

**Comment by erikandershed** [comment]
a sweet.. I am not so good in code, can you show me how to do this? 

Thanks!
