### ISSUE TITLE
animated-clip: creating the stylesheet with keyframes takes too long

### ISSUE THREAD

**Issue by valdrinkoshi** [GoogleChrome/ui-element-samples#89]
The generation of the stylesheet for the keyframes takes almost 200ms
![screen shot 2017-05-31 at 6 22 44 pm](https://cloud.githubusercontent.com/assets/6173664/26660748/c1b214b0-462e-11e7-9265-5bd7d5522794.png)

I tried saving the contents into a separate file, but it is ~3MB non-gzipped!
This could probably be reduced to half by using [animation-direction](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-direction).

**Comment by ivancuric** [comment]
Whoa. How long was the transition? And on how many elements?
The keyframe-per-frame method is probably better suited for transitions under 1.6s since over that you'll generate over 100 frames.
But for the default demo that lasts 200ms you should generate only 12 frames.

**Comment by valdrinkoshi** [comment]
I guess the bug is [this._frameTime](https://github.com/GoogleChrome/ui-element-samples/blob/gh-pages/animated-clip/menu.js#L30) being in seconds (1/60) instead of milliseconds (1000/60).

**Comment by ivancuric** [comment]
Oh wow. DERP. 😣
